### ISSUE TITLE
AttributeDecoder.Bytes

### ISSUE THREAD

**Issue by terinjokes** [mdlayher/netlink#103]
On PR #95, we discussed and added a `Bytes` function to the `AttributeEncoder` type, stating:

> It's nice and concise with a Bytes method, and general enough to make sense for many callers

If it's common to encode arbitrary bytes, it's likely common to decode them as well. A user of this API can do so with the `Do` method and a helper, but they have to be especially careful to heed the warning:

> The function fn should not retain any reference to the data b outside of the scope of the function.

If there's no objection, for API symmetry, we should add a `Bytes` method to `AttributeDecoder`.

**Comment by mdlayher** [comment]
SGTM.  A Bytes method that copies bytes b from Do and doesn't retain the original bytes is fine.

**Comment by terinjokes** [comment]
Cool, I'll submit a PR for `func (*AttributeDecoder) Bytes() []byte` then.
