### ISSUE TITLE
Receive() returning errno -1 for proc connector messages 

### ISSUE THREAD

**Issue by fearful-symmetry** [mdlayher/netlink#109]
So 225b7dcea4d3f470298e96657623b7a3f15abb1b seems to have broken my client code that reads from the linux [proc connector](http://netsplit.com/the-proc-connector-and-socket-filters) interface. Specifically, the [switch statement](https://github.com/mdlayher/netlink/blob/225b7dcea4d3f470298e96657623b7a3f15abb1b/message.go#L223) that routes `NLMSG_DONE` packets to the following conditional:

```go

	if c := nlenc.Int32(m.Data[0:4]); c != success {
		// Error code is a negative integer, convert it into
		// an OS-specific system call error
		return newError(-1 * int(c))
}
```

I'm prefacing this by saying that I am _not_ a netlink expert by any means. The first part of the payload for a proc connector message is a `cb_id` [struct](https://www.kernel.org/doc/Documentation/connector/connector.txt). Based on my (limited) understanding, for a cn_proc message, that value [should be](https://github.com/torvalds/linux/blob/master/include/uapi/linux/connector.h#L31) `CN_IDX_PROC` which is `0x1` Hence, `m.Data[0:4]` being `0x1` and the function returning -1.

I'm not sure what the reasoning is for parsing the first 32 bits in a `NLMSG_DONE` packet is, and like I said I'm not a netlink expert, so I could just be doing something wrong too.

The netlink(7) man page says that `NLMSG_DONE` terminates a multipart message, however, from what I can see, the proc connector interface sends payload data with it:

The first message is an ack from connector, second is a `fork()` event.
```
header: netlink.Header{Length:0x4c, Type:0x3, Flags:0x0, Sequence:0x45ad, PID:0x0}, data: [1 0 0 0 1 0 0 0 173 69 0 0 1 0 0 0 40 0 0 0 0 0 0 0 4 0 0 0 223 182 179 251 190 66 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
header: netlink.Header{Length:0x4c, Type:0x3, Flags:0x0, Sequence:0x5f19, PID:0x0}, data: [1 0 0 0 1 0 0 0 25 95 0 0 0 0 0 0 40 0 0 0 1 0 0 0 5 0 0 0 94 140 11 51 191 66 0 0 77 88 0 0 77 88 0 0 53 98 0 0 53 98 0 0 0 0 0 0 0 0 0 0]
```

**Comment by mdlayher** [comment]
Unfortunately I can't even remember why I made that change, but I haven't played with the proc connector at all.

Could you attach a small reproduction program and I'll see if I can look at it?

**Comment by fearful-symmetry** [comment]
The example from my [client](https://github.com/fearful-symmetry/garlic) library should work:
```go
//Open a connection to the local Proc connector instance
//This requires root.
cn, err := PCNDial()
	if err != nil {
		log.Fatalf("%s", err)
	}

//Read in events
for {
    data, err = cn.ReadPCN()

	if err != nil {
		log.Fatalf("Read fail: %s", err)
    }
	fmt.Printf("%#v\n", data)
}
```

If you don't feel like digging though someone else's libraries, here's a short tidbit that reproduces it, ran against 82b16742174c:

```go
package main

import (
	"encoding/binary"
	"fmt"
	"log"
	"syscall"

	"github.com/mdlayher/netlink"
	"github.com/mdlayher/netlink/nlenc"
)

/*
 * idx and val are unique identifiers which
 * are used for message routing and
 * must be registered in connector.h for in-kernel usage.
 */
type cbID struct {
	Idx uint32
	Val uint32
}

//The connector message struct
type cnMsg struct {
	ID    cbID
	Seq   uint32
	Ack   uint32
	Len   uint16
	Flags uint16
}

//MarshallBinary converts the entire struct into a slice, along with the proc_cn_mcast_op body
func (hdr cnMsg) MarshalBinaryAndBody(body uint32) []byte {

	bytes := make([]byte, binary.Size(hdr)+binary.Size(body))
	nlenc.PutUint32(bytes[0:4], hdr.ID.Idx)
	nlenc.PutUint32(bytes[4:8], hdr.ID.Val)
	nlenc.PutUint32(bytes[8:12], hdr.Seq)
	nlenc.PutUint32(bytes[12:16], hdr.Ack)
	nlenc.PutUint16(bytes[16:18], hdr.Len)
	nlenc.PutUint16(bytes[18:20], hdr.Flags)
	nlenc.PutUint32(bytes[20:24], body)

	return bytes
}

func main() {
	cCfg := netlink.Config{Groups: 0x1}

	//Bind
	c, err := netlink.Dial(syscall.NETLINK_CONNECTOR, &cCfg)

	if err != nil {
		log.Fatalf("Error in netlink: %s", err)
	}

	//setup process connector hdr
	cbHdr := cbID{Idx: 0x1, Val: 0x1}
	var connBody uint32 = 0x1
	cnHdr := cnMsg{ID: cbHdr, Len: uint16(binary.Size(connBody))}

	binHdr := cnHdr.MarshalBinaryAndBody(connBody)

	reqMsg := netlink.Message{
		Header: netlink.Header{
			Type: syscall.NLMSG_DONE,
		},
		Data: binHdr,
	}

	//Send request message
	msgs, err := c.Send(reqMsg)
	if err != nil {
		log.Fatalf("Execute error: %s\n %#v", err, msgs)
	}

	//Wait for our ack msg
        //Will fail here
	ack, err := c.Receive()
	if err != nil {
		log.Fatalf("could not recv ack: %v", err)
	}

	fmt.Printf("ack: %#v\n", ack)
}

```

**Comment by florianl** [comment]
Thank you @fearful-symmetry for providing a small program to reproduce the issue :+1: 

I think `checkMessage(m Message)` in `message.go` the check has to be extended to `if c := nlenc.Int32(m.Data[0:4]); c != success && isError {`

**Comment by fearful-symmetry** [comment]
Yep, that makes sense.

**Comment by mdlayher** [comment]
Thanks for the test program, it's very helpful.

Just posted #111, and your program appears to work now:

```
✔ ~/src/github.com/mdlayher/netlink/cmd/nlconn [mdl-error-check|…3] 
11:59 $ sudo ./nlconn 
ack: []netlink.Message{netlink.Message{Header:netlink.Header{Length:0x4c, Type:0x3, Flags:0x0, Sequence:0x1961, PID:0x0}, Data:[]uint8{0x1, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x61, 0x19, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0, 0x0, 0x79, 0xf8, 0x5e, 0x17, 0xe3, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}}
```

**Comment by mdlayher** [comment]
@fearful-symmetry please pull latest master and report back if your issue isn't fixed. Thanks!

**Comment by fearful-symmetry** [comment]
Will do! I would have responded sooner, but outages at work take priority. ;)
