### ISSUE TITLE
netlink: failed to build the code

### ISSUE THREAD

**Issue by xianggechishi** [mdlayher/netlink#132]
hi，I tried to compile my go program, but something went wrong with netlink. Can you help me see why?

go test *.go

# github.com/mdlayher/netlink
../../gopath/src/github.com/mdlayher/netlink/conn_linux.go:538:13: s.fd.SetDeadline undefined (type *os.File has no field or method SetDeadline)
../../gopath/src/github.com/mdlayher/netlink/conn_linux.go:542:13: s.fd.SetReadDeadline undefined (type *os.File has no field or method SetReadDeadline)
../../gopath/src/github.com/mdlayher/netlink/conn_linux.go:546:13: s.fd.SetWriteDeadline undefined (type *os.File has no field or method SetWriteDeadline)

**Comment by mdlayher** [comment]
What's the output of `go version`? The error leads me to believe that you aren't running Go 1.12, but both 1.11 and 1.12 should work.

**Comment by mdlayher** [comment]
https://golang.org/pkg/os/#File.SetDeadline was introduced in Go 1.10, which is now two stable releases out of date. This means you're running Go 1.9 or prior. Please update to Go 1.12.

**Comment by xianggechishi** [comment]
thank u~
