### ISSUE TITLE
incorrect length for attributes with NLA_F_NESTED flag set 

### ISSUE THREAD

**Issue by sbezverk** [mdlayher/netlink#140]
```
	if e.ToData > 0 {
		attrs = append(attrs, netlink.Attribute{ Type: unix.NLA_F_NESTED | unix.NFTA_RANGE_TO_DATA, Data: []byte{}})
		attrs = append(attrs, netlink.Attribute{ Type: unix.NFTA_DATA_VALUE, Data: binaryutil.BigEndian.PutUint32(e.ToData)})
	}
	data, err := netlink.MarshalAttributes(attrs)
	if err != nil {
		return nil, err
	}
```
Generates this sequence of bytes...
```
 0x04 0x00 0x04 0x80 0x08 0x00 0x01 0x00 0x07 0xee 0x00 0x00 
```
But expected:
```
 0x0c 0x00 0x04 0x80 0x06 0x00 0x01 0x00 0x07 0xee 0x00 0x00
```
Since it is a nested attribute, the total length should be 12 - 0x0c and then the actual data is 6.

**Comment by sbezverk** [comment]
@mdlayher Any chance you could check this out? It is kind of a show stopper for my project.

**Comment by mdlayher** [comment]
Please provide a runnable program with full input, rather than a code snippet. There isn't enough context for me to understand what's going on at the moment. The empty data slice in the first attribute seems suspect to me at a glance though.

I'd like to help, but it will happen as time permits with my schedule. If your needs are truly urgent, you are welcome to submit a patch yourself.

**Comment by mdlayher** [comment]
I made a small program based on your example, but it isn't clear to me what you're looking for here. There's no data specified for the first attribute, and it encodes as such (4 bytes) as well.

```go
package main

import (
	"log"

	"github.com/google/go-cmp/cmp"
	"github.com/mdlayher/netlink"
	"github.com/mdlayher/netlink/nlenc"
	"golang.org/x/sys/unix"
)

func main() {
	toData := uint32(1)

	var attrs []netlink.Attribute
	if toData > 0 {
		attrs = append(attrs, netlink.Attribute{Type: unix.NLA_F_NESTED | unix.NFTA_RANGE_TO_DATA, Data: []byte{}})
		attrs = append(attrs, netlink.Attribute{Type: unix.NFTA_DATA_VALUE, Data: nlenc.Uint32Bytes(toData)})
	}
	data, err := netlink.MarshalAttributes(attrs)
	if err != nil {
		log.Fatalf("failed to marshal: %v", err)
	}

	newattrs, err := netlink.UnmarshalAttributes(data)
	if err != nil {
		log.Fatalf("failed to unmarshal: %v", err)
	}

	// Match the actual length of each attribute.
	attrs[0].Length = 4
	attrs[1].Length = 8

	if diff := cmp.Diff(attrs, newattrs); diff != "" {
		log.Fatalf("unexpected attributes (-want +got):\n%s", diff)
	}

	log.Println(data)
	log.Println(cmp.Diff(attrs, nil))
}
```
```
$ go run main.go 
2019/06/04 15:49:05 [4 0 4 128 8 0 1 0 1 0 0 0]
2019/06/04 15:49:05   interface{}(
-       []netlink.Attribute{
-               {Length: 0x04, Type: 0x8004, Data: []uint8{}},
-               {Length: 0x08, Type: 0x01, Data: []uint8{0x01, 0x00, 0x00, 0x00}},
-       },
  )
```

**Comment by sbezverk** [comment]
@mdlayher sorry for not getting back to you earlier, I was trying to follow your advise and trying to fix it myself. I was researching the algorithm to process nested attributes, so far I found out that nested attribute length MUST include both length of a nested attribute which is normally 4 and length of data in my case is it 8, so the resulting byte slice should be `0x0c 0x00 0x04 0x80` that is nested attribute portion and then `0x06 0x00 0x01 0x00 0x07 0xee 0x00 0x00` for data. What I still have trouble to understand is how 0x06 gets calculated.

**Comment by mdlayher** [comment]
I think there is some confusion here as to how you're actually structuring these attributes.  Are you looking for something like:

```go
package main

import (
	"log"

	"github.com/mdlayher/netlink"
	"golang.org/x/sys/unix"
)

func main() {
	toData := uint32(1)

	ae := netlink.NewAttributeEncoder()
	ae.Do(unix.NLA_F_NESTED|unix.NFTA_RANGE_TO_DATA, func() ([]byte, error) {
		nae := netlink.NewAttributeEncoder()
		nae.Uint32(unix.NFTA_DATA_VALUE, toData)
		return nae.Encode()
	})

	data, err := ae.Encode()
	if err != nil {
		log.Fatalf("failed to marshal: %v", err)
	}

	log.Println(data)
}
```
```
$ go run main.go 
2019/06/04 17:03:18 [12 0 4 128 8 0 1 0 1 0 0 0]
```

I'm not sure what number you're using as input or where you're getting the number 6 from, but this has length 12 and is closer to what you seem to be looking for.

**Comment by mdlayher** [comment]
Discussed some on Slack and it appears this was most likely a misunderstanding of the package netlink attribute nesting APIs.
