### ISSUE TITLE
DIfference between vishvananda/netlink and mdlayher/netlink?

### ISSUE THREAD

**Issue by linrl3** [mdlayher/netlink#186]
Hi, I just found another netlink package in github: https://github.com/vishvananda/netlink. Does anyone know the difference between them?

**Comment by mdlayher** [comment]
See https://github.com/mdlayher/netlink#design.

This package is intended as a foundation, not as an all-in-one package. See the rest of the README for packages built on this one.

**Comment by linrl3** [comment]
@mdlayher Got it. Thank you for your reply!
