### ISSUE TITLE
netlink receive: no such file or directory

### ISSUE THREAD

**Issue by chn-lee-yumi** [mdlayher/netlink#188]
Here a C code https://gist.github.com/javiermon/43a0b9e1c07abd4b13df

I compile it and it works fine.

I was trying to rewrite it in Go, but I met an error.

```
2021/09/01 00:09:48 req: {Header:{Length:20 Type:unknown(18) Flags:request|0x300 Sequence:1 PID:7143} Data:[17 0 0 0]}
exec ok
2021/09/01 00:09:48 failed to execute request: netlink receive: no such file or directory
```

Here's my code:

```
package main

import (
	"log"
	"fmt"
	"os"
	"github.com/mdlayher/netlink"
)

func main() {
	// Speak to generic netlink using netlink
	const familyGeneric = 16

	c, err := netlink.Dial(familyGeneric, nil)
	if err != nil {
		log.Fatalf("failed to dial netlink: %v", err)
	}
	defer c.Close()

	// Ask netlink to send us an acknowledgement, which will contain
	// a copy of the header we sent to it
	req := netlink.Message{
		Header: netlink.Header{
			// Package netlink will automatically set header fields
			// which are set to zero
			Flags: netlink.Request | netlink.Dump,
			Length: 20,
			Type: 0x12,
			Sequence: 1,
			PID: uint32(os.Getpid()),
		},
    		Data: []byte{0x11,0x00,0x00,0x00},
	}
	log.Printf("req: %+v", req)

	// Perform a request, receive replies, and validate the replies
	msgs, err := c.Execute(req)
	fmt.Println("exec ok")
	if err != nil {
		log.Fatalf("failed to execute request: %v", err)
	}

	if c := len(msgs); c != 1 {
		log.Fatalf("expected 1 message, but got: %d", c)
	}

	// Decode the copied request header, starting after 4 bytes
	// indicating "success"
	var res netlink.Message
	if err := (&res).UnmarshalBinary(msgs[0].Data[4:]); err != nil {
		log.Fatalf("failed to unmarshal response: %v", err)
	}
	log.Printf("res: %+v", res)
}
```

I get the C code's netlink message in hex:

```
11 00 00 00 12 00 01 03 01 00 00 00 71 1b 00 00 11 00 00 00
| Length=17 |Type|Flags|  Sequence |    PID    |    Data   |
```

It is the same with the message in Go, except length.

I also try to change the length to 20,  then will get another error: `netlink send: netlink message header length incorrect`.

Then I comment 3 lines in `message.go`:

```
//      if ml < nlmsgHeaderLen || ml != int(m.Header.Length) {
//              return nil, errIncorrectMessageLength
//      }
```

and run again.

Then will get `netlink receive: no such file or directory`

I don't know what's wrong in my code.

**Comment by mdlayher** [comment]
You're attempting to communicate with generic netlink here but the C example communicates with route netlink.

If you want to speak rtnetlink, check out: https://github.com/jsimonetti/rtnetlink

I don't think there is a bug here but will leave open for now to see if this does what you need.

**Comment by chn-lee-yumi** [comment]
That's what I need. It works! Thanks.

> You're attempting to communicate with generic netlink here but the C example communicates with route netlink.
> 
> If you want to speak rtnetlink, check out: https://github.com/jsimonetti/rtnetlink
> 
> I don't think there is a bug here but will leave open for now to see if this does what you need.
