### ISSUE TITLE
netlink: Sequence #'s never validated

### ISSUE THREAD

**Issue by scottwis** [mdlayher/netlink#199]
The `lockedSend` method has the following signature:

```
func (c *Conn) lockedSend(m Message) (Message, error)
```

This means that the call to `fixMsg` operates on a different copy of `m` than the one that `Execute` uses. This means that the sequence number validation inside `Validate` will never run unless the caller to `Execute` uses their own sequence number generation logic.

Is this a bug?

Should `lockedSend` be changed to take in a `*Message` instead of a `Message`?

**Comment by mdlayher** [comment]
The message is both passed in and returned after modification, and that returned copy has the fields filled in. This logic is correct and I don't think there's anything to do here. Please comment if you disagree.

**Comment by scottwis** [comment]
Sorry.... I misread the code.

Thanks for the clarification.
