### ISSUE TITLE
netlink: improve debugging capabilities

### ISSUE THREAD

**Issue by mdlayher** [mdlayher/netlink#22]
Add a build tag or something that enables nice debugging with a `func debugf(format string, a ...interface{})`.

Maybe: `go build -tags=nldebug`?

**Comment by jsimonetti** [comment]
Perhaps `getenv("DEBUG")` inside `init()` ?

**Comment by mdlayher** [comment]
I recently took a shot at this using an environment variable: https://godoc.org/github.com/mdlayher/netlink#hdr-Debugging.
