### ISSUE TITLE
Could it be used for NFLOG?

### ISSUE THREAD

**Issue by ncw** [mdlayher/netlink#55]
I have a package which currently uses libnetfilter_log via cgo: https://github.com/ncw/go-nflog-acctd

I'd really like to lose the cgo out of that package.

Could this package be used for NFLOG accounting too?  If so what would need to be done?

I guess this might fall under this from the front page

> My goal for this package is to use it as a building block for the creation of other netlink family packages.

Apologies if this is a stupid question - I'm only really familiar with libnetfilter_log and I'm a bit hazy how it all fits together with netlink!

**Comment by mdlayher** [comment]
It should be possible, yes. I don't know anything about NFLOG.  My guess would be that you would want to work on a nfnetlink package to sit atop this one, and then build NFLOG on top of that.

/cc @ti-mo since he is actually working on an nfnetlink package.

**Comment by ti-mo** [comment]
Hi @ncw, don't have a lot to add to Matt's comments. This package can definitely be used to implement libnetfilter equivalents on top of. I'm currently working on getting generic Netfilter functionality implemented in a separate package, which can then be used to build Conntrack, IPset, NFLog, etc. My target is getting full Conntrack support and then building an accounting collector for conntrack events.

My time is very limited at the moment, so I don't know when I'll be able to publish something useful. Doing this in my spare time. Maybe a generic Netfilter package would be the most achievable target, so people can get to work on implementing their family of choice. This (`netlink`) package will only contain strictly Netlink-related stuff, everything else belongs in its own package.

If you're at all interested in contributing, I highly recommend you read through the source, you'll find it to be very well-documented and explanatory. Matt's articles on Medium are great and will definitely further your understanding of the protocol.

**Comment by mdlayher** [comment]
Going to close this out as it's not an issue for `netlink` proper, but feel free to reply if you have any more questions.

**Comment by mdlayher** [comment]
@ncw by the way, if you'd like to discuss your design with us, feel free to join us in #networking on Gophers Slack. I am usually around there during most of the work week, US eastern time.

**Comment by ncw** [comment]
Thanks for your helpful comments, all!  Next time I'm working on go-nflog-acctd I'll have an experiment with adding NFLOG with this package.  Last time I tried I got lost in a twisty turny maze of C macros though ;-)
