### ISSUE TITLE
nlenc: support uint8 encoding and decoding in nlenc

### ISSUE THREAD

**Issue by nak3** [mdlayher/netlink#65]
When we create a Data in Attribute, we usually need to encode a uintN
into a byte slice. However, as nlenc does not support uint8 encoding and
decoding, we have to create similar function for only uint8 in the
code. We would like to make our code consistent, so will be happy if
nlenc supports this.

**Comment by mdlayher** [comment]
Most of the reason nlenc exists is to deal with 16-bit or greater integers represented as native endian byte slices.

That said, I understand the consistency argument, and I don't mind adding a couple more functions for API symmetry if you're interested in that. Feel free to send a PR.

By the way, is the code you're working on open source? Hope this package is useful for you.

**Comment by nak3** [comment]
> By the way, is the code you're working on open source? Hope this package is useful for you.

It is still WIP, but I will make it open soon and let you know. Of course, this package is really useful as it is excellent quality and well-documented. I appreciate this package so much.

**Comment by mdlayher** [comment]
Thank you! I appreciate the sentiment, and that was certainly my goal. Would love to see what you come up with.
