### ISSUE TITLE
netlink: failed to unmarshal response

### ISSUE THREAD

**Issue by HeChuanXUPT** [mdlayher/netlink#73]
hi, 
I try to get tcp sockets status, so I have changed some code with example_test.go, made a new msg(netlink.Message) with Data(struct inet_diag_req). I define a inet_diag_req struct like C code.
The ss command send data with inet_diag_req
```
	req.nlh.nlmsg_len = sizeof(req);
	req.nlh.nlmsg_type = socktype;
	req.nlh.nlmsg_flags = NLM_F_ROOT|NLM_F_MATCH|NLM_F_REQUEST;
	req.nlh.nlmsg_pid = 0;
	req.nlh.nlmsg_seq = 123456;
	memset(&req.r, 0, sizeof(req.r));
	req.r.idiag_family = AF_INET;
	req.r.idiag_states = f->states;
	iov[0] = (struct iovec){
		.iov_base = &req,
		.iov_len = sizeof(req)
	};
	msg = (struct msghdr) {
		.msg_name = (void*)&nladdr,
		.msg_namelen = sizeof(nladdr),
		.msg_iov = iov,
		.msg_iovlen = f->f ? 3 : 1,
	};
	if (sendmsg(fd, &msg, 0) < 0)
		return -1;
```
But failed.
> failed to unmarshal response: not enough data to create a netlink message

and get some error in dmesg
> SELinux: unrecognized netlink message: protocol=4 nlmsg_type=0 sclass=32

Do you have any suggestion?

**Comment by mdlayher** [comment]
At a glance I'm guessing this is another netlink family that breaks some of the assumptions I've made in this package. I don't have time to take a look today, but if you set up a nlmon device and used tcpdump or Wireshark to capture these responses, that would be super helpful!

**Comment by HeChuanXUPT** [comment]
No, is not Generic family, it is  unix.NETLINK_INET_DIAG.
I fix my problem, add a self-define Message parse function.

**Comment by mdlayher** [comment]
Can you share your code that is interacting with INET_DIAG?  This is something we should be able to accommodate upstream instead of relying on a fork.

**Comment by mdlayher** [comment]
Ping @HeChuanXUPT, can you provide Go code that reproduces this issue?

**Comment by HeChuanXUPT** [comment]
yes, I try to make a PR a few days later

**Comment by HeChuanXUPT** [comment]
@mdlayher 
see this example
https://github.com/HeChuanXUPT/golang/blob/master/netlink/main.go

**Comment by mdlayher** [comment]
It's unclear when this was fixed, but the example program runs as expected on my machine. Closing.
