### ISSUE TITLE
Feature request: batch mode

### ISSUE THREAD

**Issue by stapelberg** [mdlayher/netlink#81]
Some nftables commands (e.g. `NFT_MSG_NEWTABLE`, see https://github.com/torvalds/linux/blob/a048a07d7f4535baa4cbad6bc024f175317ab938/net/netfilter/nf_tables_api.c#L5667) need to receive a batch of messages, i.e. message(s) which are enclosed in begin/end messages with `extra_header.res_id` `NFNL_MSG_BATCH_BEGIN` and `NFNL_MSG_BATCH_END`, respectively. These messages must then be sent in a single sendmsg syscall.

However, the netlink package currently only offers a `Send` method on type `Conn`, which serializes a single message.

To implement batching in my nftables package, I’d need a `SendMessages` (or similar) method, which would serialize multiple messages at once.

Assuming the feature request makes sense to you, would you like to add this yourself, or would you prefer a pull request?

**Comment by mdlayher** [comment]
A PR would be excellent! TIL that netlink can do batches of messages at once from the userspace side of things.
