### ISSUE TITLE
functionality for setting socker opts

### ISSUE THREAD

**Issue by worldyn** [mdlayher/netlink#85]
There should be a function for setting socket opts more general than for example JoinGroup. The use case for me is that I need t oset options from the socket options list from the netlink man(7). Please tell me if there is an alternative that already exists in the library.

**Comment by worldyn** [comment]
I work with a component that needs to enable NETLINK_LISTEN_ALL_NSID which can be done with with setsockopt with the parameters SOL_NETLINK, NETLINK_LISTEN_ALL_NSID and where optval is a pointer to a variable = 1 and the optlen is the size of that var.

**Comment by mdlayher** [comment]
Apologies for the delay, I was out of town. I started thinking about this today, and I came up with the following:

```go
type ConnFlag int

const (
    ListenAllNSID ConnFlag = 1
)

func (c *Conn) SetFlag(flag ConnFlag, enable bool) error {}
```

I think that this would allow us to add a small API that could deal with any possible flags that can be toggled. Thoughts?

**Comment by worldyn** [comment]
Yes, looks good! However, to avoid confusion, I think it should be named SocketOpt/ConnOpt instead since the term Flag is used in netlink messages.

**Comment by mdlayher** [comment]
Makes sense to me. I'll look into doing that in the next couple of days hopefully.
