### ISSUE TITLE
Closing a Netlink socket with ongoing Receive() call

### ISSUE THREAD

**Issue by ti-mo** [mdlayher/netlink#92]
Hi Matt

I'm trying to cleanly terminate a Netlink socket listening on a multicast group.

```go
func main() {
	conn, err := netlink.Dial(0xc, nil) // NETLINK_NETFILTER
	if err != nil {
		log.Fatal(err)
	}

	err = conn.JoinGroup(10) // Non-existent multicast group (Receive() will never return)
	if err != nil {
		log.Fatal(err)
	}

	recvChan := make(chan []netlink.Message)

	// Start a blocking receive
	go func() {
		recv, err := conn.Receive()
		if err != nil {
			log.Fatal(err)
		}
		recvChan <- recv
	}()

	// Make sure goroutine enters Receive()
	// time.Sleep(50 * time.Millisecond)

	err = conn.Close()
	if err != nil {
		log.Fatal(err)
	}

	log.Println(<-recvChan)
}
```

This uncovers two issues:

1. A race condition: running this program multiple times in sequence yields different results. One is a panic:

```
panic: send on closed channel
goroutine 4 [running]:
github.com/mdlayher/netlink.(*sysSocket).do(0xc4200bc0a0, 0xc4200f6000)
    /home/timo/go/src/github.com/mdlayher/netlink/conn_linux.go:356 +0xa8
```

.. that can be avoided by closing the channel after the WaitGroup merges. This causes a deadlock in the test suite, so this might invalidate some assumptions you've made in other places.

```go
func (s *sysSocket) Close() error {
	...
	s.wg.Wait()
	close(s.funcC)
```

2. `Receive()` is non-interruptible. (uncomment the `Sleep()` in the example)

If there's no valid Netlink message coming in (like in the example above), `Receive()` will hang forever. I've tried closing the fd from the main thread by executing `unix.Close()` directly instead of queueing it with `s.do()`, but this (expectedly) doesn't interrupt the syscall either. It will only yield when a message is read from the socket.

I know this is not directly an issue with the library itself, but it would be pleasant to have a solution or workaround. Is there anything you could think of? A quick search hinted that syscalls can be interrupted by signals, not sure if this is something we could implement.

**Comment by mdlayher** [comment]
Thanks for looking into this. I'll see what I can do. I do have an issue open to see if we can integrate with the runtime network poller properly, but it may be difficult due to the need for certain system calls.

Either way we should fix the closing synchronization.

**Comment by florianl** [comment]
I'm facing the same issue:

`panic: send on closed channel
	panic: send on closed channel

goroutine 17 [running]:
github.com/mdlayher/netlink.(*sysSocket).do(0xc42000a0c0, 0xc4200ba1e0)
	/home/flo/go/src/github.com/mdlayher/netlink/conn_linux.go:356 +0xa8
github.com/mdlayher/netlink.(*sysSocket).Sendmsg(0xc42000a0c0, 0xc4200aa1a0, 0x1c, 0x1c, 0x0, 0x0, 0x0, 0x4e8320, 0xc4200aa1c0, 0x0, ...)
	/home/flo/go/src/github.com/mdlayher/netlink/conn_linux.go:435 +0x11d
github.com/mdlayher/netlink.(*conn).Send(0xc42000a180, 0x504010000001c, 0x275cd4fb09a8, 0xc4200a0310, 0xc, 0x10, 0xc42004a698, 0x488fbc)
	/home/flo/go/src/github.com/mdlayher/netlink/conn_linux.go:127 +0x11b
github.com/mdlayher/netlink.(*Conn).Send(0xc42006a240, 0x504010000001c, 0x275cd4fb09a8, 0xc4200a0310, 0xc, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
	/home/flo/go/src/github.com/mdlayher/netlink/conn.go:208 +0x130
github.com/mdlayher/netlink.(*Conn).Execute(0xc42006a240, 0x5040100000000, 0x0, 0xc4200a0310, 0xc, 0x10, 0x7fcec73bc6c8, 0x0, 0x2, 0xc4200a02f0, ...)
`

`panic: send on closed channel

goroutine 17 [running]:
github.com/mdlayher/netlink.(*sysSocket).do(0xc42000a0c0, 0xc4200f8180)
	/home/flo/go/src/github.com/mdlayher/netlink/conn_linux.go:361 +0xa8
github.com/mdlayher/netlink.(*sysSocket).Sendmsg(0xc42000a0c0, 0xc4200ba140, 0x1c, 0x1c, 0x0, 0x0, 0x0, 0x4e8a80, 0xc4200ba160, 0x0, ...)
	/home/flo/go/src/github.com/mdlayher/netlink/conn_linux.go:440 +0x11d
github.com/mdlayher/netlink.(*conn).Send(0xc42000a180, 0x504010000001c, 0x2f6e0f93d04e, 0xc4200b0320, 0xc, 0x10, 0xc42005c690, 0xc42005c690)
	/home/flo/go/src/github.com/mdlayher/netlink/conn_linux.go:127 +0x11b
github.com/mdlayher/netlink.(*Conn).Send(0xc42006a240, 0x504010000001c, 0x2f6e0f93d04e, 0xc4200b0320, 0xc, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
	/home/flo/go/src/github.com/mdlayher/netlink/conn.go:208 +0x130
github.com/mdlayher/netlink.(*Conn).Execute(0xc42006a240, 0x5040100000000, 0xf93d04e, 0xc4200b0320, 0xc, 0x10, 0x7f3bcbaf76c8, 0x0, 0x2, 0xc4200b0310, ...)
`
I've played with `syscall.SetNonblock(s.fd, true)`, but was not successful.

**Comment by ti-mo** [comment]
@florianl `SetNonblock()` should work, are you sure you're not running it with `s.do()`? It needs to be run from the main thread, otherwise it's queued after the ongoing `Receive()`.

**Comment by florianl** [comment]
i'm pretty sure, I placed it not correctly.

**Comment by mdlayher** [comment]
Just put up #94.  Since this issue describes two separate problems, can you please move the uninterruptible reads problem to a new issue?  Thanks.
